In [16]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import AdaBoostClassifier
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
from sklearn.metrics import accuracy_score,confusion_matrix

In [4]:
breast = pd.read_csv("D:/Term-2/MachineLearning/breast_cancer.csv")
breast.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

            ...             radius_worst  texture_worst  perimeter_worst  \
0           ...                    25.38          17.33           184.60   
1           ...                    24.99          23.41           158.80   
2           ...                    23.57          25.53           152.50   
3           ...                    14.91          26.50            98.87   
4           ...                    22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 32 columns]

In [5]:
breast.isnull().sum()

id                         0
diagnosis                  0
radius_mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
smoothness_worst           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [6]:
y=breast['diagnosis']
#y=y.drop(['id'],axis=1)
x = breast.drop(['diagnosis'],axis=1)
x=x.drop(['id'],axis=1)
x1 = pd.get_dummies(x)

In [9]:
x_train,x_test,y_train,y_test  = train_test_split(x1,y,test_size =0.3,random_state=42)

In [12]:
ad=AdaBoostClassifier()
ad.fit(x_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [13]:
ad_pred = ad.predict(x_test)
accuracy_score(ad_pred,y_test)

0.9766081871345029

# Select K best Feature-using the concept of correlation

In [86]:
#Features extraction
test = SelectKBest(score_func=chi2,k=5)
fit=test.fit(x,y)

In [87]:
#summarixe scores
np.set_printoptions(precision=3)
print(fit.scores_)

[2.661e+02 9.390e+01 2.011e+03 5.399e+04 1.499e-01 5.403e+00 1.971e+01
 1.054e+01 2.574e-01 7.431e-05 3.468e+01 9.794e-03 2.506e+02 8.759e+03
 3.266e-03 6.138e-01 1.045e+00 3.052e-01 8.036e-05 6.371e-03 4.917e+02
 1.744e+02 3.665e+03 1.126e+05 3.974e-01 1.931e+01 3.952e+01 1.349e+01
 1.299e+00 2.315e-01]


In [83]:
reduce_x = fit.transform(x)
reduce_x

array([[ 122.8 , 1001.  ,  153.4 ,  184.6 , 2019.  ],
       [ 132.9 , 1326.  ,   74.08,  158.8 , 1956.  ],
       [ 130.  , 1203.  ,   94.03,  152.5 , 1709.  ],
       ...,
       [ 108.3 ,  858.1 ,   48.55,  126.7 , 1124.  ],
       [ 140.1 , 1265.  ,   86.22,  184.6 , 1821.  ],
       [  47.92,  181.  ,   19.15,   59.16,  268.6 ]])

In [77]:
x_train,x_test,y_train,y_tesh=train_test_split(reduce_x,y,test_size=0.2,random_state=42)

In [78]:
ad=AdaBoostClassifier()
ad.fit(x_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [79]:
ad_pred = ad.predict(x_test)
accuracy_score(ad_pred,y_test)

0.9649122807017544

# Reduntant feature elimination

In [90]:
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression


In [109]:
model = LogisticRegression()
rfe = RFE(model,4)
fit=rfe.fit(x,y)

In [110]:
print(rfe.n_features_)

4


In [111]:
print(rfe.support_)

[ True False False False False False  True False False False False False
 False False False False False False False False  True False False False
 False False  True False False False]


In [112]:
print(fit.ranking_)

[ 1 11 13 27 14 18  1  3  8 22 23  9  4  7 25 24 15 20 19 26  1 10  5 21
 16  6  1  2 17 12]


In [114]:
reduce_x  =fit.transform(x)
reduce_x

array([[17.99 ,  0.3  , 25.38 ,  0.712],
       [20.57 ,  0.087, 24.99 ,  0.242],
       [19.69 ,  0.197, 23.57 ,  0.45 ],
       ...,
       [16.6  ,  0.093, 18.98 ,  0.34 ],
       [20.6  ,  0.351, 25.74 ,  0.939],
       [ 7.76 ,  0.   ,  9.456,  0.   ]])

In [106]:
x_train,x_test,y_train,y_test=train_test_split(reduce_x,y,test_size=0.2,random_state=42)

In [119]:
ad=AdaBoostClassifier()
ad.fit(x_train,y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None,
          learning_rate=1.0, n_estimators=50, random_state=None)

In [120]:
ad_pred = ad.predict(x_test)
accuracy_score(ad_pred,y_test)

0.9298245614035088

# Feature elimination using ExtraTreeClassfier(uses Gini index concept)

In [127]:
from sklearn.ensemble import ExtraTreesClassifier 

In [128]:
model = ExtraTreesClassifier()
model.fit(x,y)

ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=10, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [130]:
model.feature_importances_

array([0.077, 0.011, 0.02 , 0.089, 0.008, 0.039, 0.071, 0.045, 0.017,
       0.007, 0.016, 0.005, 0.067, 0.021, 0.007, 0.007, 0.01 , 0.003,
       0.006, 0.004, 0.019, 0.024, 0.02 , 0.193, 0.013, 0.008, 0.039,
       0.132, 0.009, 0.011])

In [125]:
import pickle

In [126]:
pickle.dump(ad,'ad.pkl')

TypeError: file must have a 'write' attribute