In [1]:
import os
import pandas as pd
import numpy as np

In [2]:
os.chdir('c://users//administrator//desktop')
em  = pd.read_csv('employees_attrition.csv')
em.shape

(1470, 35)

In [3]:
em.head(2)

Age  Attrition     BusinessTravel  DailyRate              Department  \
0   41          1      Travel_Rarely       1102                   Sales   
1   49          0  Travel_Frequently        279  Research & Development   

   DistanceFromHome  Education EducationField  EmployeeCount  EmployeeNumber  \
0                 1          2  Life Sciences              1               1   
1                 8          1  Life Sciences              1               2   

           ...           RelationshipSatisfaction StandardHours  \
0          ...                                  1            80   
1          ...                                  4            80   

   StockOptionLevel  TotalWorkingYears  TrainingTimesLastYear WorkLifeBalance  \
0                 0                  8                      0               1   
1                 1                 10                      3               3   

   YearsAtCompany YearsInCurrentRole  YearsSinceLastPromotion  \
0               6                  4                        0   
1              10                  7                        1   

   YearsWithCurrManager  
0                     5  
1                     7  

[2 rows x 35 columns]

In [4]:
em_dum = pd.get_dummies(em)

In [5]:
x = em_dum.drop(['Attrition'],axis = 1 )
y = em_dum['Attrition']

In [6]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score as acs
from sklearn.model_selection import train_test_split as tts

In [7]:
x_tr,x_ts,y_tr,y_ts = tts(x,y,test_size = 0.3)

# DECISION TREE

In [9]:
model = DecisionTreeClassifier(criterion= 'gini',random_state=15,max_depth=1)

In [10]:
model.fit(x_tr,y_tr)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=1,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=15,
            splitter='best')

In [11]:
model.score(x_tr,y_tr)

0.8299319727891157

In [12]:
model.score(x_ts,y_ts)

0.8594104308390023

# RANDOM FOREST

In [13]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
model_rf = RandomForestClassifier(n_estimators= 151 , n_jobs=2)

In [16]:
model_rf.fit(x_tr,y_tr)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=151, n_jobs=2,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [18]:
model_rf.score(x_tr,y_tr)

1.0

In [19]:
model_rf.score(x_ts,y_ts)

0.8752834467120182

In [20]:
model_rf2 = RandomForestClassifier(n_estimators= 251 , n_jobs=2)

In [21]:
model_rf2.fit(x_tr,y_tr)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=251, n_jobs=2,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [22]:
model_rf2.score(x_tr,y_tr)

1.0

In [23]:
model_rf2.score(x_ts,y_ts)

0.8798185941043084

In [51]:
importances = model_rf2.feature_importances_
importances

array([0.06541167, 0.04884923, 0.03957056, 0.01730437, 0.        ,
       0.04264962, 0.02452822, 0.04241942, 0.02207858, 0.01631146,
       0.02654958, 0.05905406, 0.04418548, 0.03417936, 0.02902232,
       0.00444761, 0.02355462, 0.        , 0.02965228, 0.04574337,
       0.02212252, 0.02333116, 0.04497561, 0.02607645, 0.02153118,
       0.0291285 , 0.00311884, 0.01163787, 0.007019  , 0.00245519,
       0.00813503, 0.00857021, 0.00226943, 0.00730749, 0.00809243,
       0.00673739, 0.0026171 , 0.00715684, 0.00624936, 0.00632448,
       0.00320178, 0.00190017, 0.00803421, 0.00088193, 0.00322256,
       0.0009282 , 0.00702791, 0.00668236, 0.0066229 , 0.00549714,
       0.00780742, 0.01788875, 0.        , 0.03101862, 0.02891816])

In [41]:
imp = {}
for i in range(len(x_tr.columns)):
    imp[i] = importances[i]

In [50]:
#OR

indices = np.argsort(importances)[::-1]
indices

array([ 0, 11,  1, 19, 22, 12,  5,  7,  2, 13, 53, 18, 25, 14, 54, 10, 23,
        6, 16, 21, 20,  8, 24, 51,  3,  9, 27, 31, 30, 34, 42, 50, 33, 37,
       46, 28, 35, 47, 48, 39, 38, 49, 15, 44, 40, 26, 36, 29, 32, 41, 45,
       43, 17,  4, 52], dtype=int64)

# GRID SEARCH CV

In [24]:
from sklearn.model_selection import GridSearchCV

In [25]:
model_rf3 = RandomForestClassifier()

In [55]:
model_grid = GridSearchCV(model_rf3 , param_grid= {'n_estimators' :[151,251,351,451]},cv=5,scoring= 'f1')

In [56]:
model_grid.fit(x_tr,y_tr)

GridSearchCV(cv=5, error_score='raise-deprecating',
       estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
       fit_params=None, iid='warn', n_jobs=None,
       param_grid={'n_estimators': [151, 251, 351, 451]},
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring='f1', verbose=0)

In [57]:
model_grid.best_params_

{'n_estimators': 151}

# RANDOMIZED SEARCH CV

In [33]:
from sklearn.model_selection import RandomizedSearchCV

In [35]:
model_rans = RandomizedSearchCV(model_rf3 ,n_iter=100,param_distributions= {'n_estimators' : [251,351,451,401,501,201,301]},cv =3)

In [36]:
model_rans.fit(x_tr,y_tr)

C:\Users\Administrator\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:271: UserWarning: The total space of parameters 7 is smaller than n_iter=10. Running 7 iterations. For exhaustive searches, use GridSearchCV.
  % (grid_size, self.n_iter, grid_size), UserWarning)


RandomizedSearchCV(cv=3, error_score='raise-deprecating',
          estimator=RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators='warn', n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False),
          fit_params=None, iid='warn', n_iter=10, n_jobs=None,
          param_distributions={'n_estimators': [251, 351, 451, 401, 501, 201, 301]},
          pre_dispatch='2*n_jobs', random_state=None, refit=True,
          return_train_score='warn', scoring=None, verbose=0)

In [38]:
model_rans.best_params_

{'n_estimators': 251}

In [54]:
np.linspace(20,200,10)                   ## linearly spaced values between start and stop

array([ 20.,  40.,  60.,  80., 100., 120., 140., 160., 180., 200.])

In [6]:
x =list(range(101,501,50))

In [7]:
print(x)

[101, 151, 201, 251, 301, 351, 401, 451]
