In [31]:
import numpy as np
from sklearn.decomposition import TruncatedSVD

In [2]:
from scipy.linalg import svd

In [3]:
A=np.array([[1,2,3,4,5,5,7,8,9,10],
          [11,12,13,14,15,16,17,18,19,20],
          [21,22,23,24,25,26,27,28,29,30]])

In [4]:
#Singluar value decompostion
u,s,vt=svd(A)

In [6]:
u.shape,s.shape,vt.shape

((3, 3), (3,), (10, 10))

In [7]:
u

array([[-0.18782165,  0.89552539,  0.40343191],
       [-0.51403431,  0.2603792 , -0.81729517],
       [-0.83695385, -0.36088357,  0.41142593]])

In [8]:
s

array([96.90512365,  7.29719273,  0.38469213])

In [9]:
vt

array([[-2.41661423e-01, -2.57540973e-01, -2.73420524e-01,
        -2.89300074e-01, -3.05179625e-01, -3.19120974e-01,
        -3.36938726e-01, -3.52818277e-01, -3.68697827e-01,
        -3.84577378e-01],
       [-5.23332537e-01, -4.14383652e-01, -3.05434766e-01,
        -1.96485880e-01, -8.75369940e-02, -1.01310013e-01,
         1.30360778e-01,  2.39309664e-01,  3.48258549e-01,
         4.57207435e-01],
       [ 1.38109245e-01,  1.31773449e-01,  1.25437653e-01,
         1.19101858e-01,  1.12766062e-01, -9.42283442e-01,
         1.00094471e-01,  9.37586751e-02,  8.74228794e-02,
         8.10870837e-02],
       [-2.54569664e-01, -1.78876572e-01, -1.51218362e-01,
         9.25756208e-01, -7.26581421e-02, -6.71728979e-15,
        -6.94868420e-02, -6.79011920e-02, -6.63155420e-02,
        -6.47298920e-02],
       [-2.65985755e-01, -5.63730445e-02, -1.20300703e-01,
        -6.14878648e-02,  9.28595645e-01, -6.76868295e-15,
        -9.12373346e-02, -1.01153825e-01, -1.11070315e-01,
        -1.

In [10]:
#create  m*n signma matrix
sigma =np.zeros((A.shape[0],A.shape[1]))
sigma

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [11]:
A.shape[0]

3

In [16]:
#populate signma with n*n  diagonal matrix
sigma[:A.shape[0],:A.shape[0]]=np.diag(s)
sigma

array([[96.90512365,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  7.29719273,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.38469213,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ]])

In [15]:
A1=u.dot(sigma.dot(vt))
A1

array([[ 1.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [18]:
sigma1=sigma[:,:2]
sigma1

array([[96.90512365,  0.        ],
       [ 0.        ,  7.29719273],
       [ 0.        ,  0.        ]])

In [20]:
vt1=vt[:2,:]
vt1

array([[-0.24166142, -0.25754097, -0.27342052, -0.28930007, -0.30517962,
        -0.31912097, -0.33693873, -0.35281828, -0.36869783, -0.38457738],
       [-0.52333254, -0.41438365, -0.30543477, -0.19648588, -0.08753699,
        -0.10131001,  0.13036078,  0.23930966,  0.34825855,  0.45720744]])

In [23]:
b1=np.round(u.dot(sigma1.dot(vt1)))
b1

array([[ 1.,  2.,  3.,  4.,  5.,  5.,  7.,  8.,  9., 10.],
       [11., 12., 13., 14., 15., 16., 17., 18., 19., 20.],
       [21., 22., 23., 24., 25., 26., 27., 28., 29., 30.]])

In [26]:
t1=u.dot(sigma1)
t1

array([[-18.20087975,   6.53482136],
       [-49.81255873,   1.90003719],
       [-81.10511673,  -2.63343696]])

In [30]:
t2=A.dot(vt1.T)
t2


array([[-18.20087975,   6.53482136],
       [-49.81255873,   1.90003719],
       [-81.10511673,  -2.63343696]])

In [32]:
svd=TruncatedSVD(n_components=2)
svd.fit(A)

TruncatedSVD(algorithm='randomized', n_components=2, n_iter=5,
       random_state=None, tol=0.0)

In [37]:
result=svd.transform(A)
result

array([[18.20087975,  6.53482136],
       [49.81255873,  1.90003719],
       [81.10511673, -2.63343696]])

In [38]:
svd.explained_variance_,svd.explained_variance_ratio_roop0;

(array([659.49616267,  14.01006364]), array([0.9791266 , 0.02080016]))